### PR TITLE
Restore actions/index.html use-case & rename sub-READMEs to explainer.md

### PR DESCRIPTION
**Pull request by jan-ivar**

### CODE REVIEW

**Review by dontcallmedom — APPROVED** [review]

**Comment by eladalon1983** [comment]
(Approved modulo changes discussed [here](https://github.com/w3c/mediacapture-handle/pull/28#issuecomment-1064220523).)

**Comment by jan-ivar** [comment]
> Recreate README.md with a redirection to the explainer.

I added an `identity/README.md` with:
```
Moved to [explainer.md](explainer.md).
```
Hope that's what you meant (I found no way to redirect using markup or HTML that the github file viewer would follow).

**Comment by eladalon1983** [comment]
The changes to `actions/index.html` look like a rebase-error, or...?

**Comment by jan-ivar** [comment]
> The changes to `actions/index.html` look like a rebase-error, or...?

What do you mean? It's restoring the "Problem Description" and use case # 1, and LGTM.

**Review by eladalon1983 — APPROVED** [review]

**Comment by jan-ivar** [comment]
@eladalon1983 we forgot to discuss this PR at this morning's Editors' call. Since it's marked `Editorial` and you and I both approve of it, are you ok if we merge it now? (the README is using strikethrough font on the actions link rn which is unfortunate).

**Comment by eladalon1983** [comment]
I've gone ahead and done s/WICG/w3c, as this was clearly a left-over from before the repo migrated.
Yes, I'm fine merging. I'll do that now.

**Pull request merged**
