### PR TITLE
Specify requirement of exposure: tab-capture

### LINKED ISSUE #43: Tab capture restriction
The Abstract says "It describes a mechanism for [tab capture](https://www.w3.org/TR/screen-capture/#dfn-browser) only."

However, Section 5.2 says: 

"If the track in question is not a video track, or is not the result of a capture of a display surface, then the user agent MUST return null."

This seems to allow a CaptureHandle to be returned in scenarios other than tab capture.

### PR DESCRIPTION
**Pull request by eladalon1983**
Fixes #43.

### CODE REVIEW

**Review by aboba — APPROVED** [review]

**Comment by eladalon1983** [comment]
@jan-ivar, PTAL.

**Review by jan-ivar — APPROVED** [review]

**Comment by eladalon1983** [comment]
@jan-ivar, shall we merge this now, or do you think such PRs should wait until the Thursday meeting?

**Comment by jan-ivar** [comment]
The chairs are working on defining a clearer process for CfA which includes freezing a doc during the CfA, but I think that advice is good for CfC on FPWD as well: it seems generally a good idea to not touch a document during a CfC on FPWD to ensure everyone reviewing the doc is reading the same thing. I'd generally want to wait till Thursday anyway.

**Comment by eladalon1983** [comment]
Very well. Let's wait.

**Comment by jan-ivar** [comment]
Of course we forgot to merge PRs from this repo this morning. 🤦 In the interest of time, I'm merging this and the editorial #48, #49 and #51 now since people might be referring to this doc a lot this week already. cc @eladalon1983 @alvestrand @aboba @youennf

**Comment by eladalon1983** [comment]
Fine by me. Thank you for the heads-up.

**Pull request merged**
