### PR TITLE
Fix event.captureHandle() when not observable

### LINKED ISSUE #53: CaptureHandleChangeEvent.captureHandle() when navigating
The spec currently reads:
> CaptureHandleChangeEvent.[captureHandle()](https://w3c.github.io/mediacapture-handle/identity/#dom-capturehandlechangeevent-capturehandle):
>
> The track's [CaptureHandle](https://w3c.github.io/mediacapture-handle/identity/#dom-capturehandlechangeevent-capturehandle) at the time the event was fired, as observable by the capturing application. If not observable by the capturing application, all of CaptureHandle's fields will be set to their default value - the empty [DOMString](https://webidl.spec.whatwg.org/#idl-DOMString).

It makes more sense to return the exact same CaptureHandle as would a call to [MediaStreamTrack.getCaptureHandle()](https://w3c.github.io/mediacapture-handle/identity/#capture-handle-via-getcapturehandle). When there is no [observable](https://w3c.github.io/mediacapture-handle/identity/#dfn-observable) CaptureHandle, that means returning `null`. So:

> CaptureHandleChangeEvent.[captureHandle()](https://w3c.github.io/mediacapture-handle/identity/#dom-capturehandlechangeevent-capturehandle):
>
> The track's [CaptureHandle](https://w3c.github.io/mediacapture-handle/identity/#dom-capturehandlechangeevent-capturehandle) at the time the event was fired, as observable by the capturing application. If not observable by the capturing application, returns `null`, as `MediaStreamTrack.getCaptureHandle()` does.

--

Noteworthy - there's a discussion on issue #50 over a suggestion to strip `captureHandle()` out of the event altogether. If that proposal is adopted, the current discussion would be rendered moot. However, until we settle that particular discussion, it makes sense to perform a localized fix here.

### PR DESCRIPTION
**Pull request by eladalon1983**
Fix #53.

### CODE REVIEW

**Comment by eladalon1983** [comment]
Thanks for raising this, @beaufortfrancois. Your thoughts about this fix?

**Comment by beaufortfrancois** [comment]
Non-owner LGTM

Note that having https://github.com/w3c/mediacapture-handle/issues/50 settled may make this PR obsolete.
@jan-ivar What are your thoughts on https://github.com/w3c/mediacapture-handle/issues/50#issuecomment-1114964918?

**Comment by eladalon1983** [comment]
> Note that having #50 settled may make this PR obsolete.

Yes, I've mentioned as much on the issue accompanying this PR. It's not clear to me if we can resolve issue #50 quickly, so in the meantime, I'd like to land this incremental improvement to the spec.

**Comment by eladalon1983** [comment]
Rendered irrelevant by other changes. Closing.

**Pull request closed without merging**
